### ISSUE TITLE
setting up 30-minute output for MCS tracking  

### ISSUE THREAD

**Issue by weiming9115** [FlexTRKR/PyFLEXTRKR#48]
Hi, I am using GPM-IMERGE and MERGE-IR, 30-minute temporal resolution, for MCS tracking. I set up "
datatimeresolution: 0.5" to inform the data temporal resolution (0.5 hour), but it doesn't give me outputs of 30-minute when checking the "base_time" of tracked MCSs, only hourly time stamps.

Is it possible to identify the objects every 30 minutes by setting parameters in config.yml? because I only see the "hourly" option in "config_imerg_mcs_tbpf_example.yml", which probably led me to the hourly outputs:

----
idclouds_hourly: 1  # 0:  No, 1:  Yes
idclouds_minute: 0  # 0 or 30 min, which minute mark to use the Tb data
idclouds_dt_thresh: 5  # [minute], time difference allowed between actual data and idclouds_minute

Thank you,
Wei-Ming

**Comment by feng045** [comment]
Hi,
I think if you set `idclouds_hourly: 0`, the code should use all available times in each of the input files. 

Although you may want to also set `clouddatasource` to something other than 'gpmirimerg' (as in the provided IMERG config example). This is because for our previous working developing the global MCS tracking dataset ([Feng et al. 2021 JGR](https://doi.org/10.1029/2020JD034202)), we kept the 30 min MERGED-IR (Tb) data but averaged the 30 min IMERG precipitation data to hourly.  Hence, the tracking code looks for a specific flag `clouddatasource: 'gpmirimerg'`, if that flag is set, then it only uses IMERG from the first time in the hourly file, which is probably not what you want.

What does your GPM-IMERGE and MERGE-IR look like?  Do you have two 30 min frames in an hourly file?  If that's the case, what I described above should work.

Best,
Zhe

**Comment by weiming9115** [comment]
Hi,

Got it. I used `idclouds_hourly: 1` because I was wondering if `idclouds_hourly: 0` may skip the idclouds process. Maybe a comment in the config file help, which says "using NO for all available timeframes"? 

I do have two timeframes in an hourly data for GPM and MERGE-IR, so it should work fine as you described. Thank you so much!

Best,
Wei-Ming

**Comment by feng045** [comment]
Added a comment to explain this parameter in #51. Closing this issue.
